project:
  type: website
  output-dir: docs

website:
  title: "SE D&A GitHub Guides"
  description: "test site"
  sidebar:
    foreground: "black"
    # background: "#EBF5FF"
    background: "#005eb833"
    style: "docked"
    search: true
    contents:
      - intro-to-github.qmd
      - section: "GitHub Guides"
        contents:
          - first-repo.qmd
          - github-desktop.qmd
          - r-studio.qmd
          - vs-code.qmd
          - databricks-github.qmd
          - fdp.qmd
      - section: "Principles"
        contents:
          - understanding-code.qmd
          - qasar.qmd
      - section: "Placeholder"
        contents:
          - another-page.qmd
      
format:
  html:
    toc: true
    css: styles.css

execute:
  freeze: auto
